# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: About
    url: /#about
    weight: 10
  - name: Demo
    url: /#demo
    weight: 20
  - name: How It Works
    url: /#steps
    weight: 30
  - name: Computer Vision
    url: /#vision
    weight: 35
  - name: Tech Stack
    url: /#tech
    weight: 40
  - name: Team
    url: /#team
    weight: 50
  - name: Code
    url: /#code
    weight: 55
